language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-15
    - android-22
    - android-16
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - extra-google-m2repository





before_install:
    - chmod +x gradlew
