language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-15
    - android-24
    - android-16
    - sys-img-armeabi-v7a-android-24
    - extra-android-m2repository
    - extra-google-m2repository





before_install:
    - echo $ENCODED_KEYSTORE | sed 's/ /\n/g' | base64 --decode >> ${HOME}/keystore.jks
    - echo 'export KEYSTORE=${HOME}/xobyx/XContactj2/keystore.jks' >> $BASH_ENV
    - chmod +x gradlew

deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: $GITHUB_TOKEN
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    