language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-15
    - android-21
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - extra-google-google_play_services





