version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-24-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: echo $ENCODED_KEYSTORE | sed 's/ /\n/g' | base64 --decode >> ${HOME}/repo/keystore.jks
      - run:
          name: Download Dependencies
          command: echo 'export KEYSTORE=${HOME}/repo/keystore.jks' >> $BASH_ENV
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: build app
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/outputs
          destination: reports
      - store_test_results:
          path: app/build/outputs/apk
